#!/usr/bin/bash

#This script will installq Apache, MySQL, and PHP and PHP modules for Apache and MySQL

function upgradePackages(){
sudo apt update -y && sudo apt upgrade -y

}
function apache(){
sudo apt install apache2 -y
}

function mysql(){
sudo apt install mysql-server -y
}

function php(){
sudo apt install php libapache2-mod-php php-mysql -y
}


validation=0
while [ $validation -eq 0 ]
do
        echo -e "Hello $USER \n You are about to install Apache, MySQL, and PHP and PHP modules for Apache and MySQL. \n Do you want to proceed? Type y for yes and n for no"
        read response
        if [[ $response == "y" ]]
        then
                upgradePackages
                apache
                mysql
                php
                echo "yes worked"
                validation=1
        elif [[ $response == "n" ]]
        then
                echo "Goodbye"
                exit
        else
                echo "Wrong input"
        fi

done
